### ISSUE TITLE
Tester plugin automated "Test SAGA is installed" fails on macOS b1 build

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-core-tests#10]
```
Test name: Core Tests-Test SAGA is installed. QGIS-89 (1)
Test result:Test failed at step 'Run unit test' with message:
(<type 'exceptions.AssertionError'>, AssertionError('unexpectedly None',), <traceback object at 0x123b7b488>)
  File "/Library/Boundless/Desktop/1.1/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/boundless/.qgis2/python/plugins/coretests/tests/packages_tests.py", line 25, in testSaga
    self.assertIsNotNone(folder)
  File "/Library/Boundless/Desktop/1.1/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 960, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Boundless/Desktop/1.1/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)

Traceback (most recent call last):
  File "/Users/boundless/.qgis2/python/plugins/qgistester/testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "/Users/boundless/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute
    return func()
  File "/Users/boundless/.qgis2/python/plugins/qgistester/test.py", line 66, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AssertionError'>, AssertionError('unexpectedly None',), <traceback object at 0x123b7b488>)
  File "/Library/Boundless/Desktop/1.1/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/boundless/.qgis2/python/plugins/coretests/tests/packages_tests.py", line 25, in testSaga
    self.assertIsNotNone(folder)
  File "/Library/Boundless/Desktop/1.1/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 960, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Boundless/Desktop/1.1/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
```

**Comment by volaya** [comment]
The issue here is that the SAGA installation path in Desktop is not among the expected ones, so the test for the SAGA folder fails. However, saga works fine, since it seems that SAGA is added to PATH when Desktop is run, so executing "saga_cmd" directly (without prepending the SAGA folder path) works.

I have removed the test for SAGA folder, but I would like to get confirmation (@dakcarto) that SAGA is always going to be in PATH and we can assume that calling it without folder path is going to work

**Comment by dakcarto** [comment]
@volaya, yes, on both Win and macOS `saga_cmd` will be on PATH for Desktop 1.1.0.

For 1.1.1+ that may change for macOS, as there may be more that one SAGA available with OSGeo4Mac. In which case, I will force the LTS version (2.3.x) to be symlinked into the main build of Desktop, thereby ensuring it is on PATH again.

**Comment by volaya** [comment]
Cool, that makes sense. Then this can be closed
