### ISSUE TITLE
Python error when running manual "QGIS core tests" within Tester plugin

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-core-tests#11]
```
UnboundLocalError: local variable 'e' referenced before assignment 
Traceback (most recent call last):
File "/Users/gmanghi/.qgis2/python/plugins/qgistester/plugin.py", line 80, in test
self.widget.startTesting()
File "/Users/gmanghi/.qgis2/python/plugins/qgistester/testerwidget.py", line 73, in startTesting
self.runNextTest()
File "/Users/gmanghi/.qgis2/python/plugins/qgistester/testerwidget.py", line 92, in runNextTest
self.runNextStep()
File "/Users/gmanghi/.qgis2/python/plugins/qgistester/testerwidget.py", line 181, in runNextStep
self.testContainsError("%s\n%s" % (str(e), traceback.format_exc()))
UnboundLocalError: local variable 'e' referenced before assignment
```

The error is non blocking, meaning that the manual tests can be run despite the error.

**Comment by volaya** [comment]
This error is not in this plugin, but in the tester plugin. I have just fixed it
