### ISSUE TITLE
python error for test "Test core plugins are loaded"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-core-tests#12]
On Windows 10 and BD 1.1.1

```
Test name: Core Tests-Test core plugins are loaded. QGIS-55
Test result:Test contains an error at step 'Run unit test':
(<type 'exceptions.AssertionError'>, AssertionError('False is not true',), <traceback object at 0x00000000245A1948>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:/Users/gio/.qgis2/python/plugins\coretests\tests\packages_tests.py", line 43, in testCorePluginsAreLoaded
    self.assertTrue(p in active_plugins)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\case.py", line 424, in assertTrue
    raise self.failureException(msg)

Traceback (most recent call last):
  File "C:/Users/gio/.qgis2/python/plugins\qgistester\testerwidget.py", line 124, in runNextStep
    execute(step.function)
  File "C:\Users\gio\.qgis2\python\plugins\qgistester\extlibs\qgiscommons-2.0.4-py2.7.egg\qgiscommons2\gui\__init__.py", line 233, in execute
    return func()
  File "C:/Users/gio/.qgis2/python/plugins\qgistester\test.py", line 67, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AssertionError'>, AssertionError('False is not true',), <traceback object at 0x00000000245A1948>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:/Users/gio/.qgis2/python/plugins\coretests\tests\packages_tests.py", line 43, in testCorePluginsAreLoaded
    self.assertTrue(p in active_plugins)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\unittest\case.py", line 424, in assertTrue
    raise self.failureException(msg)
```

**Comment by gioman** [comment]
Sorry for the noise, the tested core plugins must be enabled.
