### ISSUE TITLE
Automated test fail

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-core-tests#6]
Please note that GRASS7 in Processing seems to work ok, so seems just a test issue.

[FAILED] Test GRASS is installed QGIS-89 (2)
Failed at step Run unit test with message

Traceback (most recent call last): File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 115, in runNextStep execute(step.function) File "C:/Users/boundless/.qgis2/python/plugins\qgistester\utils.py", line 61, in execute return func() File "C:/Users/boundless/.qgis2/python/plugins\qgistester\test.py", line 64, in _runTest raise Exception(desc) Exception: (, AssertionError("u'GRASS folder is not configured.\\nPlease configure it before running GRASS algorithms.' is not None",), ) File "C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\Python27\lib\unittest\case.py", line 331, in run testMethod() File "C:/Users/boundless/.qgis2/python/plugins\coretests\tests\packages_tests.py", line 36, in testGrass self.assertIsNone(msg) File "C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\Python27\lib\unittest\case.py", line 956, in assertIsNone self.fail(self._formatMessage(msg, standardMsg)) File "C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\Python27\lib\unittest\case.py", line 412, in fail raise self.failureException(msg)

**Comment by gioman** [comment]
after the latest commits error is (same test failing)

Test name: Core Tests-Test GRASS is installed QGIS-89 (2)
Test result:Test failed at step 'Run unit test' with message:
Traceback (most recent call last):
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 115, in runNextStep
    execute(step.function)
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\utils.py", line 61, in execute
    return func()
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\test.py", line 64, in _runTest
    raise Exception(desc)
Exception: (<type 'exceptions.AttributeError'>, AttributeError("class Grass7Utils has no attribute 'GRASS7_FOLDER'",), <traceback object at 0x000000001A562988>)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\osgeo4w\apps\Python27\lib\unittest\case.py", line 331, in run
    testMethod()
  File "C:/Users/boundless/.qgis2/python/plugins\coretests\tests\packages_tests.py", line 33, in testGrass
    folder = ProcessingConfig.getSetting(Grass7Utils.GRASS7_FOLDER)

**Comment by gioman** [comment]
fixed with latest patch.
